name: DeployInfrastructure

on:
  workflow_dispatch:
    inputs:
        github_owner:
          description: 'GitHub Owner'     
          required: true
        github_repo:
          description: 'GitHub Repo'
          required: true
        github_token:
          description: 'GitHub Token'
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
        github_owner: ${{ github.event.inputs.github_owner }}
        github_repo: ${{ github.event.inputs.github_repo }}
        github_token: ${{ github.event.inputs.github_token }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      # Test user input
      - run: |
          echo $github_owner $github_repo
        
      # Login to Azure with SP
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Replace runner value
      - run: |            
          sed -i "s/{github_owner}/$github_owner/g" init.yaml
          sed -i "s/{github_repo}/$github_repo/g" init.yaml
          sed -i "s/{github_token}/$github_token/g" init.yaml
      
      # Provision infra
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        with:
          # Specify the script here
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/10createinfra.azcli
            $GITHUB_WORKSPACE/10createinfra.azcli
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          path: |
            $GITHUB_WORKSPACE
