name: DeployInfra

on:
  workflow_dispatch:
    inputs:
        github_owner:
          description: 'GitHub Owner'     
          required: true
        github_repo:
          description: 'GitHub Repo'
          required: true
        github_token:
          description: 'GitHub Token'
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - run: |
          echo "GitHub Owner: ${{ github.event.inputs.github_owner }}"
          echo "GitHub Repo: ${{ github.event.inputs.github_repo }}"
          github_owner=${{ github.event.inputs.github_owner }}
          github_repo=${{ github.event.inputs.github_repo }}
          github_token=${{ github.event.inputs.github_token }}
      - run: |
          echo $github_owner $github_repo $github_token
        
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
