name: CICD

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup go environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      # Check go version
      - run: go version
          
      # Checks-out source code from repo
      - name: Check out repo from showmetwo/TechChallengeApp
        uses: actions/checkout@v2
        with:
          repository: showmetwo/TechChallengeApp
          path: techchallengeapp
      
      - name: Check out repo from showmetwo/TCS
        uses: actions/checkout@v2
        with:
          repository: showmetwo/TCS
          path: tcs
      
      - run: |
          mkdir temp
          cp -a techchallengeapp/. temp/
          cp -a tcs/. temp/
          
      # Login to Azure with SP
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        with:
          # Specify the script here
          inlineScript: |
            chmod +x temp/15configapp.azcli
            temp/15configapp.azcli
      
      # Build go source code
      - name: Build source code with sh
        run: |
          chmod +x temp/build.sh
          temp/build.sh
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: application
          path: |
            temp/dist
  
  deploy:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: self-hosted
    strategy:
      max-parallel: 2
      matrix:
        count: [1, 2]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: mkdir -p /artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          # Destination path
          path: /artifact
          
      - name: Upload a Deploy Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: deployment
          path: |
            ${{ github.workspace }}
      
