name: CICD

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup go environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      
      - run: |
          go version
            
      # Checks-out source code from repo
      - name: Check out repo from showmetwo/TechChallengeApp
        uses: actions/checkout@v2
        with:
          repository: showmetwo/TechChallengeApp
      
      # Build go source code
      - name: Build source code with sh
        run: |
          chmod +x $GITHUB_WORKSPACE/build.sh
          $GITHUB_WORKSPACE/build.sh
      
      - run: |
          mkdir /temp
          cp -a $GITHUB_WORKSPACE/. /temp/
          pwd
          ls -l
          ls /temp
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: application
          path: |
            dist
  
  
