name: CICD

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup go environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      
      - run: |
          go version
            
      # Checks-out source code from repo
      - name: Check out repo from showmetwo/TechChallengeApp
        uses: actions/checkout@v2
        with:
          repository: showmetwo/TechChallengeApp
      
      - name: Check out repo from showmetwo/TCS
        uses: actions/checkout@v2
        with:
          repository: showmetwo/TCS
          path: tcs
      
      # Login to Azure with SP
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        with:
          # Specify the script here
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/tcs/15configapp.azcli
            $GITHUB_WORKSPACE/tcs/15configapp.azcli
      
      - run: |
          pwd
          echo $GITHUB_WORKSPACE
          ls -l
          cat conf.toml
          cat tcs/conf.toml
          cp $GITHUB_WORKSPACE/tcs/conf.toml $GITHUB_WORKSPACE/conf.toml
      
      # Build go source code
      - name: Build source code with sh
        run: |
          chmod +x $GITHUB_WORKSPACE/build.sh
          $GITHUB_WORKSPACE/build.sh
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: application
          path: |
            dist
