name: ContinuesIntegration

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup go environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      # Check go version
      - run: go version
          
      # Checks-out source code from repo
      - name: Check out repo from servian/TechChallengeApp
        uses: actions/checkout@v2
        with:
          repository: servian/TechChallengeApp
      
      # Build go source code
      - name: Build source code with sh
        run: |
          chmod +x $GITHUB_WORKSPACE/build.sh
          $GITHUB_WORKSPACE/build.sh
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: application
          path: |
            dist
  deploy:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: mkdir -p /artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          # Destination path
          path: /artifact
